apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stable-diffusion.fullname" . }}-sd-stable-diffusion-diffusion
  labels:
    io.kompose.service: diffusion
  {{- include "stable-diffusion.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
spec:
  replicas: {{ .Values.sd.replicas }}
  selector:
    matchLabels:
      io.kompose.service: diffusion
    {{- include "stable-diffusion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.service: diffusion
      {{- include "stable-diffusion.selectorLabels" . | nindent 8 }}
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
    spec:
      containers:
      - env:
        - name: HIP_VISIBLE_DEVICES
          value: {{ quote .Values.sd.diffusion.env.hipVisibleDevices
            }}
        - name: COMMANDLINE_ARGS
          value: {{ quote .Values.sd.diffusion.env.commandlineArgs
            }}
        - name: WEBUI_USER
          value: {{ quote .Values.sd.diffusion.env.webuiUser }}
        - name: WEBUI_PASSWORD
          value: {{ quote .Values.sd.diffusion.env.webuiPassword
            }}
        image: {{ .Values.sd.diffusion.image.repository }}:{{ .Values.sd.diffusion.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.sd.diffusion.imagePullPolicy
          }}
        livenessProbe:
          exec:
            command:
            - curl --fail http://localhost:7860/sdapi/v1/options || exit 1
          failureThreshold: 3
          initialDelaySeconds: 900
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 30
        name: diffusion
        ports:
        - containerPort: 7860
          name: 7860tcp
          protocol: TCP
        resources: {{- toYaml .Values.sd.diffusion.resources |
          nindent 10 }}
        securityContext: {{- toYaml .Values.sd.diffusion.containerSecurityContext
          | nindent 10 }}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /dockerx/stable-diffusion-webui/models
          name: diffusion-models
        - mountPath: /dockerx/stable-diffusion-webui/venv
          name: diffusion-venv
        - mountPath: /dockerx/stable-diffusion-webui/extensions
          name: diffusion-extensions
      dnsConfig:
        nameservers:
        - 1.1.1.1
      dnsPolicy: None
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations: {{- toYaml .Values.sd.diffusion.tolerations
          | nindent 6 }}
      volumes:
      - name: diffusion-models
        persistentVolumeClaim:
          claimName: {{ include "stable-diffusion.fullname" . }}-models
      - name: diffusion-venv
        persistentVolumeClaim:
          claimName: {{ include "stable-diffusion.fullname" . }}-venv
      - name: diffusion-extensions
        persistentVolumeClaim:
          claimName: {{ include "stable-diffusion.fullname" . }}-ext
