apiVersion: v1
kind: Service
metadata:
  name: {{ include "stable-diffusion.fullname" . }}-diffusion
  labels:
    io.kompose.service: diffusion
  {{- include "stable-diffusion.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
spec:
  type: {{ .Values.diffusion.type }}
  selector:
    io.kompose.service: diffusion
  {{- include "stable-diffusion.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.diffusion.ports | toYaml | nindent 2 }}