apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stable-diffusion.fullname" . }}-ext
  labels:
  {{- include "stable-diffusion.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.ext.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.ext.storageClass | quote }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "stable-diffusion.fullname" . }}-ext
  labels:
    type: local
  {{- include "stable-diffusion.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: {{ .Values.pvc.ext.path }}
  storageClassName: {{ .Values.pvc.ext.storageClass | quote }}
