pvc:
  ext:
    storageClass: manual
    storageRequest: 5Gi
    path: /media/muflo/Volume10TB/AI/kube-sd-ext
  models:
    storageClass: manual
    storageRequest: 500Gi
    path: /media/muflo/Volume10TB/AI/kube-sd-models
  venv:
    storageClass: manual
    storageRequest: 15Gi
    path: /media/muflo/Volume10TB/AI/kube-sd-venv
diffusion:
  ports:
  - name: "7860"
    port: 7860
    targetPort: 7860
  type: ClusterIP
sd:
  diffusion:
    containerSecurityContext:
      capabilities:
        add:
        - SYS_PTRACE
      privileged: true
    env:
      commandlineArgs: --listen --device-id=0 --precision full --no-half --medvram
        --skip-version-check --api --gradio-auth-path auth --enable-insecure-extension-access
        --opt-sub-quad-attention
      hipVisibleDevices: "1"
      webuiPassword: ThisIsMySuperSecurePassword.123
      webuiUser: admin
    image:
      repository: moophlo/stable-diffusion
      tag: v1.10.0_rocm5.2
    imagePullPolicy: Always
    resources:
      limits:
        amd.com/gpu: "1"
    replicas: 1
    tolerations:
      - effect: NoSchedule
        key: gpu
        operator: Equal
        value: "true"
