apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rainloop.fullname" . }}
  labels:
    app: {{ include "rainloop.name" . }}
    chart: {{ include "rainloop.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rainloop.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "rainloop.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "rainloop.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "rainloop.fullname" . }}-pvc

